# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: immortalwrt-master-R66s

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 22 * * 5

permissions:
  contents: read

jobs:

  build_openwrt:

    name: Build OpenWrt Firmware

    runs-on: ubuntu-latest

    steps:
      - name: Space cleanup and Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install build-essential git libncurses5-dev libpython3-dev python3-pyelftools swig
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt autoclean
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Checkout OpenWrt
        uses: actions/checkout@v3

      - name: Clone source
        run: |
          rm -rf .git/ .github/ *
          git clone --depth=1 --branch=master https://github.com/immortalwrt/immortalwrt.git ./

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_lunzn_fastrhino-r66s=y
          CONFIG_LUCI_LANG_zh_Hans=y
          CONFIG_NGINX_HTTP_QUIC=y
          CONFIG_PACKAGE_autocore=y
          CONFIG_PACKAGE_kmod-tcp-bbr=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-ddns-go=y
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk is not set
          CONFIG_PACKAGE_luci-app-openclash=y
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_luci-nginx=y
          CONFIG_PACKAGE_mariadb-server=y
          CONFIG_PACKAGE_mariadb-server-base=y
          CONFIG_PACKAGE_php8=y
          CONFIG_PACKAGE_php8-cgi=y
          CONFIG_PACKAGE_php8-fastcgi=y
          CONFIG_PACKAGE_php8-fpm=y
          CONFIG_PACKAGE_php8-mod-bcmath=y
          CONFIG_PACKAGE_php8-mod-calendar=y
          CONFIG_PACKAGE_php8-mod-ctype=y
          CONFIG_PACKAGE_php8-mod-curl=y
          CONFIG_PACKAGE_php8-mod-dom=y
          CONFIG_PACKAGE_php8-mod-exif=y
          CONFIG_PACKAGE_php8-mod-fileinfo=y
          CONFIG_PACKAGE_php8-mod-filter=y
          CONFIG_PACKAGE_php8-mod-ftp=y
          CONFIG_PACKAGE_php8-mod-gd=y
          CONFIG_PACKAGE_php8-mod-gettext=y
          CONFIG_PACKAGE_php8-mod-gmp=y
          CONFIG_PACKAGE_php8-mod-iconv=y
          CONFIG_PACKAGE_php8-mod-imap=y
          CONFIG_PACKAGE_php8-mod-intl=y
          CONFIG_PACKAGE_php8-mod-ldap=y
          CONFIG_PACKAGE_php8-mod-mbstring=y
          CONFIG_PACKAGE_php8-mod-mysqli=y
          CONFIG_PACKAGE_php8-mod-mysqlnd=y
          CONFIG_PACKAGE_php8-mod-opcache=y
          CONFIG_PACKAGE_php8-mod-openssl=y
          CONFIG_PACKAGE_php8-mod-pcntl=y
          CONFIG_PACKAGE_php8-mod-pdo=y
          CONFIG_PACKAGE_php8-mod-pdo-mysql=y
          CONFIG_PACKAGE_php8-mod-pdo-pgsql=y
          CONFIG_PACKAGE_php8-mod-pdo-sqlite=y
          CONFIG_PACKAGE_php8-mod-pgsql=y
          CONFIG_PACKAGE_php8-mod-phar=y
          CONFIG_PACKAGE_php8-mod-session=y
          CONFIG_PACKAGE_php8-mod-shmop=y
          CONFIG_PACKAGE_php8-mod-simplexml=y
          CONFIG_PACKAGE_php8-mod-snmp=y
          CONFIG_PACKAGE_php8-mod-soap=y
          CONFIG_PACKAGE_php8-mod-sockets=y
          CONFIG_PACKAGE_php8-mod-sodium=y
          CONFIG_PACKAGE_php8-mod-sqlite3=y
          CONFIG_PACKAGE_php8-mod-sysvmsg=y
          CONFIG_PACKAGE_php8-mod-sysvsem=y
          CONFIG_PACKAGE_php8-mod-sysvshm=y
          CONFIG_PACKAGE_php8-mod-tokenizer=y
          CONFIG_PACKAGE_php8-mod-xml=y
          CONFIG_PACKAGE_php8-mod-xmlreader=y
          CONFIG_PACKAGE_php8-mod-xmlwriter=y
          CONFIG_PACKAGE_php8-mod-zip=y
          CONFIG_PACKAGE_php8-pecl-dio=y
          CONFIG_PACKAGE_php8-pecl-http=y
          CONFIG_PACKAGE_php8-pecl-imagick=y
          CONFIG_PACKAGE_php8-pecl-krb5=y
          CONFIG_PACKAGE_php8-pecl-mcrypt=y
          CONFIG_PACKAGE_php8-pecl-raphf=y
          CONFIG_PACKAGE_php8-pecl-redis=y
          CONFIG_PACKAGE_redis-server=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Download packages
        run: make download -j16

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
