name: mihomo-R66s-23-wifi

on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 21 * * *

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      
      - name: Set up Ubuntu repositories to default US mirror
        run: |
          sudo cp /etc/apt/sources.list /etc/apt/sources.list.backup

          sudo bash -c 'echo "deb http://security.ubuntu.com/ubuntu focal-security main universe" > /etc/apt/sources.list.d/ubuntu-focal-sources.list'
          sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse" > /etc/apt/sources.list'
          sudo bash -c 'echo "deb-src http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb-src http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb-src http://archive.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse" >> /etc/apt/sources.list'
          sudo bash -c 'echo "deb-src http://archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse" >> /etc/apt/sources.list'

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt-get -y purge azure-cli* docker* ghc* llvm* firefox* google* dotnet* aspnetcore* powershell* mysql* php* mongodb* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install build-essential git libncurses-dev libpython3-dev python3-setuptools python3-pyelftools swig
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt autoclean
          sudo -E apt clean
          sudo -E timedatectl set-timezone "Asia/Shanghai"

      - name: Download and Extract Source Code
        run: |
          rm -rf .git/ .github/ *
          OPENWRT_LATEST=$(curl -s "https://api.github.com/repos/immortalwrt/immortalwrt/tags" | grep '"name": "v24' | head -n 1 | cut -d '"' -f 4)
          MIHOMO_LATEST=$(curl -s "https://api.github.com/repos/morytyann/OpenWrt-mihomo/tags" | grep 'name' | head -n 1 | cut -d '"' -f 4)
          wget "https://github.com/immortalwrt/immortalwrt/archive/refs/tags/$OPENWRT_LATEST.zip" -O openwrt_latest.zip
          wget "https://github.com/morytyann/OpenWrt-mihomo/archive/refs/tags/$MIHOMO_LATEST.zip" -O mihomo_latest.zip
          OP_TAG=$(echo "$OPENWRT_LATEST" | sed 's/^v//')
          MH_TAG=$(echo "$MIHOMO_LATEST" | sed 's/^v//')
          unzip -q openwrt_latest.zip -d .
          unzip -q mihomo_latest.zip -d .
          mv "immortalwrt-$OP_TAG"/* .
          mv "OpenWrt-mihomo-$MH_TAG"/luci-app-mihomo package/
          mv "OpenWrt-mihomo-$MH_TAG"/mihomo package/
          rm -rf "immortalwrt-$OP_TAG" "OpenWrt-mihomo-$MH_TAG" openwrt_latest.zip mihomo_latest.zip
        
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          cat >> .config <<EOF
          CONFIG_TARGET_rockchip=y
          CONFIG_TARGET_rockchip_armv8=y
          CONFIG_TARGET_rockchip_armv8_DEVICE_lunzn_fastrhino-r66s=y
          CONFIG_PACKAGE_kmod-rtw88-8822bu=y
          CONFIG_PACKAGE_kmod-tcp-bbr=y
          CONFIG_PACKAGE_luci-app-acme=y
          CONFIG_PACKAGE_luci-app-ddns-go=y
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk is not set
          CONFIG_PACKAGE_luci-app-ksmbd=y
          CONFIG_PACKAGE_luci-app-mihomo=y
          CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-vlmcsd=y
          CONFIG_PACKAGE_openvpn-openssl=y
          CONFIG_PACKAGE_wpad=y
          CONFIG_TARGET_ROOTFS_PARTSIZE=1024
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Download packages
        run: make download -j16
  
      - name: Build firmware
        run: |
          make -j$(nproc)
  
      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
  
      - name: Upload buildinfo
        uses: actions/upload-artifact@master
        with:
          name: immortalwrt_buildinfo
          path: ./artifact/buildinfo/
  
      - name: Upload package
        uses: actions/upload-artifact@master
        with:
          name: immortalwrt_package
          path: ./artifact/package/
  
      - name: Upload firmware
        uses: actions/upload-artifact@master
        with:
          name: immortalwrt_firmware
          path: ./bin/targets/
